### ISSUE TITLE
CI tests

### ISSUE THREAD

**Issue by zramsay** [monax/sqlsol#4]

**Comment by anurag308** [comment]
$ node examples/EggTracker/server.js
After entering the above command I am getting the following error:
Following is the stack trace:

module.js:472
   throw err;
   ^

Error: Cannot find module '/home/user1/.eris/apps/eris-sqlsol-master/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node'
   at Function.Module._resolveFilename (module.js:470:15)
   at Function.Module._load (module.js:418:25)
   at Module.require (module.js:498:17)
   at require (internal/module.js:20:19)
   at Object.<anonymous> (/home/user1/.eris/apps/eris-sqlsol-master/node_modules/sqlite3/lib/sqlite3.js:4:15)
   at Module._compile (module.js:571:32)
   at Object.Module._extensions..js (module.js:580:10)
   at Module.load (module.js:488:32)
   at tryModuleLoad (module.js:447:12)
   at Function.Module._load (module.js:439:3)
