### ISSUE TITLE
Problems with fs-extra package and node server failing

### ISSUE THREAD

**Issue by andytudhope** [monax/sqlsol#7]
OS: Ubuntu 16.04
eris version: 0.12.0
node version: 7.2.1
npm version: 3.10.10

I cloned the github repo and ran `npm install`. All ran as expected (though I can provide a full gist if you need it).

Then, when attempting to run `node examples/EggTracker/server.js` it failed with this error:
```module.js:472
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bc_admin/.eris/apps/eris-sqlsol/examples/EggTracker/server.js:3:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Easily fixed by either changing the package.json to include fs-extra as a dependency or update the server.js file (line 3) to no longer require it. I installed fs-extra in the node_modules folder and then ran `node examples/EggTracker/server.js` again. This time it failed with a more nasty stack trace and am not sure where to go from here:
```
#
# Fatal error in ../deps/v8/src/api.cc, line 1051
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#

==== C stack trace ===============================

    node(v8::base::debug::StackTrace::StackTrace()+0x16) [0x15bea96]
    node(V8_Fatal+0xe8) [0x15bbbd8]
    node(v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)+0x107) [0x9f0717]
    /home/bc_admin/.eris/apps/eris-sqlsol/node_modules/eris-db/node_modules/ws/node_modules/bufferutil/build/Release/bufferutil.node(init(v8::Local<v8::Object>)+0x250) [0x7f404a4662e0]
    node(node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)+0x365) [0x12ef905]
    node(v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))+0x129) [0xa1fda9]
    node() [0xa97d9d]
    node(v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)+0xec) [0xa98bcc]
    [0x21d30c8063a7]
Illegal instruction (core dumped)
```

**Comment by andytudhope** [comment]
OK, so you can ignore all of this, because the latestEC branch seems to fix most of it.

Still had to manually `npm install restify` in the node_modules folder and then it all fired. However, whether I try on a Mac or an Ubuntu VM, I seem to get to same unhandled promise rejection whenever I try to set anything using the `/secret/wordsgohere` route.

`curl http://localhost:1212/secret/iWantToSetUpAnEggNow

(node:88523) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'args' of undefined`

However, using that route in the browser results in the same messages in the terminal, but this output on the actual webpage:

"Random egg created with ID: 1\n"

However, the rest of the routes all seem to work and return the correct id in the terminal, though calling them shows an error in the browser because obviously the set didn't work properly. Navigating to, for instance, http://localhost:1212/eggs/1 returns this message:

"Egg not Found\n"
